### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [AryaChakraborty/articulus_rag#12]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by Sakshi007c** [comment]
CONTRIBUTING.md helps to guide throughout the open source project, which enables fixing bugs and enhance the project. This repository is not having having the file.
Can you please assign this issue to me?

**Comment by suhanipaliwal** [comment]
Could you please assign this issue to me because I was the one who raised this issue initially.
