### ISSUE TITLE
missing Installation steps in readme.md file

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [AryaChakraborty/articulus_rag#14]
### Describe the feature
missing Installation steps in readme.md file.
i  will add how to install the project in the local system and how to clone it 

### Implement features
Look through the GitHub issues for features. Anything tagged with "enhancement" and "help wanted" is open to whoever wants to implement it.

**If you are proposing a feature:**
- Explain in detail how it would work.
- Keep the scope as narrow as possible, to make it easier to implement.
- Remember that this is a volunteer-driven project and that contributions are welcome :)

### Write Documentation
We can always use more documentation on the web in blog posts, articles, and such.

**Comment by amroodh** [comment]
I'm a contributor under GSSoC 24
I want to work on this issue.
The readme do not have forking instructions and it will be beneficial for contributors to know the steps from README.
It lacks the list of Python Libraries required -  Example pip install streamlit.

**Comment by AryaChakraborty** [comment]
@amroodh You can work on the ranking algorithm (I will guide you if you want), since I believe a lot of contributors are already working on enhancing the README. And also, we do not have the idea clear, what the final website should look like. So I think most of the bandwidth should be aligned in that direction.

**Comment by amroodh** [comment]
great works for me, should i create an issue for that?

**Comment by AryaChakraborty** [comment]
Yeah, make it sound like "enhancing the search algorithm"
