### ISSUE TITLE
Rmove unrequired packages from requirements.txt

### ISSUE THREAD

**Issue by thakurboy004** [AryaChakraborty/articulus_rag#17]
### Describe the bug
While installing the packages from requirements.txt many files create dependency issues and I have noticed most of them are not even the required packages for running the project.

**If you are reporting a bug, please include:**
- My operating system is Windows 10 
- I tried setting up the file in a `conda` environment but the file already contains `conda` packages. So please keep that in mind while contributing to this issue
- For your reference here is the bug I am talking about:
![Screenshot (20)](https://github.com/AryaChakraborty/articulus_rag/assets/75372728/560ca52a-c914-4365-9515-066045b9df90)

**Comment by ASIF-Kh** [comment]
Hi, I am the contributor of gssoc 2024, I have required knowledge to solve this issue, kindly assign me this.

**Comment by thakurboy004** [comment]
Sure, You can Start working on it
