### ISSUE TITLE
Making a gradio web app and then deploying it on huggingface spaces 

### ISSUE THREAD

**Issue by 4darsh-Dev** [AryaChakraborty/articulus_rag#19]
### Implement features

- Making gradio web app which can be deployed further on huggingface hub space very easily and can be accessed freely.
- Gradio web app will allows us to access the app via API call to the endpoint.
- Frontend of the project can be hosted on vercel and ML models can be accessed by api call from gradio seamlessly.

### Additional context
I've previously deployed my gradio web app for my project of Dark Pattern Detection which uses a fine tuned BERT model for multi class classification of dark pattern categories . 
Link : https://huggingface.co/spaces/4darsh-Dev/dark_pattern_detector_app_v2

**Comment by 4darsh-Dev** [comment]
Assign it to me as a GSSoC contributor

**Comment by 4darsh-Dev** [comment]
Can you assign it to me ?

**Comment by AryaChakraborty** [comment]
@gratusrichard @4darsh-Dev thanks for showing interest. Will assign you the task, once y'all accept the collab. invite.

**Comment by gratusrichard** [comment]
@gratusrichard  Done

**Comment by 4darsh-Dev** [comment]
@AryaChakraborty  I've accepted the invite .. Can I start working on it ?

**Comment by 4darsh-Dev** [comment]
@AryaChakraborty should i also add a documentation.md for gradio web app

**Comment by AryaChakraborty** [comment]
@4darsh-Dev yeah, you can

**Comment by 4darsh-Dev** [comment]
@AryaChakraborty  I've raised the PR please review it.

**Comment by 4darsh-Dev** [comment]
@AryaChakraborty  You can deploy it live on huggingface hub by creating an account, or if you want I can deploy it there with articulus rag name.
