### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Princegupta101** [AryaChakraborty/articulus_rag#2]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow [these](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-using-a-template) instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by shrehs** [comment]
Hello! I'm excited to express my interest in contributing to GSSOC 24 by working on adding a code of conduct. While my past projects have not been primarily focused on documentation, I have a solid understanding of machine learning techniques, including data preprocessing, model development, and evaluation. I'm deeply committed to open-source initiatives and believe that my skills can be effectively utilized to establish a welcoming and inclusive environment through a comprehensive code of conduct. With my eagerness to embrace new challenges and dedication to continuous learning, I'm confident in my ability to deliver meaningful contributions to this endeavor. I'm thrilled about the prospect of collaborating with the team and contributing to the success of GSSOC 24. Thank you for considering my request.

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign me this task.

**Comment by AryaChakraborty** [comment]
@suhanipaliwal you can create a new issue like adding fine-tuning support for llms, or try to fix the stopgap solution for the text extraction that we are currently using. You can also try solving easier issues like adding vectordb support, for starters.

If you need any help or context, please feel free to connect, or drop a mail. Will be happy to help.

**Comment by shrehs** [comment]
Hello, I have created a pull request for the code of conduct. Please let me know if it is ok or any other changes is required. Thank you!
