### ISSUE TITLE
Enhance the Contributing.md

### ISSUE THREAD

**Issue by PradnyaGaitonde** [AryaChakraborty/articulus_rag#27]
As the instructions to contribute using GitHub Desktop are missing in the current Contributing.md file, I would like to add those detailed instructions.

I believe that by providing clear and comprehensive guidance, we can encourage more contributors to participate in the project, especially those who prefer using GitHub Desktop for their contributions.

Could you please assign me the issue related to adding GitHub Desktop contribution instructions under gssoc24? I am excited about the opportunity to contribute to the project and help streamline the contribution process for others.

**Comment by 21atha** [comment]
Please, assign me this issue
