### ISSUE TITLE
Website not deployed

### ISSUE THREAD

**Issue by Apurv7777** [AryaChakraborty/articulus_rag#28]
- Chrome 

- Error : 404 Page not found

![Screenshot_20240515_224843_Chrome](https://github.com/AryaChakraborty/articulus_rag/assets/65327303/e1ff8216-3b1f-4ef3-9a3b-10ce3f60a596)

**Comment by sbk2k1** [comment]
@Apurv7777 Due to memory constraints we are not deploying it currently.
