### ISSUE TITLE
Enhance Readme.md file 

### ISSUE THREAD

**Issue by aasthakourav20** [AryaChakraborty/articulus_rag#31]
Hey @AryaChakraborty the readme file can be more enhanced and updated  , adding more features ,  guidelines . As Readme file plays an important role in user/Contributor convenience . 
Kindly assign this issue to me under GSSoC'24 .

**Comment by khushi-igupta** [comment]
Hello @aasthakourav20 I am a GsSOC'24 contributor and I would like to work on this issue. Can you please assign it to me?
