### ISSUE TITLE
Enhance Logging for Better Debugging

### ISSUE THREAD

**Issue by Vikranth3140** [AryaChakraborty/articulus_rag#42]
## Description:

The current logging mechanism in the project is minimal and does not provide enough information for debugging. Improving the logging can help developers understand the flow and catch issues more efficiently.

## Tasks:

1. Implement logging at different levels (info, debug, error).
2. Add logging statements to key functions to trace the execution flow and capture important variables.

**Comment by AryaChakraborty** [comment]
we already have this functionality
