### ISSUE TITLE
Learn.md

### ISSUE THREAD

**Issue by Princegupta101** [AryaChakraborty/articulus_rag#5]
Learn repos should have a LEARN.md file to teach student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn.

Reference: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/Learn.md

**Comment by hasmithagunda123** [comment]
Hello please assign this task to me under gssoc24

**Comment by AryaChakraborty** [comment]
@hasmithagunda123 you can create a video or a simpler form of documentation, such that folks can get started with contributing easily without going through tons of documentation. We already have most of the parts covered in the main readme file.

**Comment by KavyaBS123** [comment]
Hey @AryaChakraborty I am  a GSSOC Contributor can you please assign this issue to me I would love to work on this!

**Comment by AryaChakraborty** [comment]
@KavyaBS123 can you create a readme file regarding this, today?

**Comment by KavyaBS123** [comment]
Sure, I will

**Comment by hasmithagunda123** [comment]
Sure I will

> @hasmithagunda123 you can create a video or a simpler form of documentation, such that folks can get started with contributing easily without going through tons of documentation. We already have most of the parts covered in the main readme file.

**Comment by AryaChakraborty** [comment]
added the learn.md, meanwhile y'all can work on the demo video
