### ISSUE TITLE
Girlscript Summer of Code Introduction/Tracking

### ISSUE THREAD

**Issue by Princegupta101** [AryaChakraborty/articulus_rag#6]
👋 Hi @AryaChakraborty ,

I am Prince,web developer Girlscript Summer of Code. I'll be collaborating with you on preparing your repo for GSSoC'24 Program

Why are these changes required?
After Analysing last year's contributions and feedback it would be great for students to have a couple of standard readme files on the repo to understand what the project is all about and some issues detailing what they can contribute. This will help you to see increased engagement in your repository as well.

As mentioned students get a chance to learn step by step, how to build this project as well as invite mentors to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for Girlscript summer of code 2024 on 10th May.

This issue will serve as a tracking issue to track all issues related to GSSoC'24. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch.

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated.

I look forward to working with you :octocat:

- [x] #1
- [x] #2
- [x] #3 
- [x] #4
- [x] #5

**Comment by Rhythm1710** [comment]
Hi! I have a good understanding of Flask and RAG. I would like to contribute on this project.

**Comment by hasmithagunda123** [comment]
Hello I have good knowledge with ml please assign this task to me

**Comment by thenu2003** [comment]
Hello !  I have good knowledge with Machine learning , Flask , Rag and HuggingFace . I would like to contribute on this project

**Comment by AryaChakraborty** [comment]
@thenu2003 you can probably open a new issue and look into creating a streamlit app, utilizing all the capabilities of the framework. Meanwhile, I will try to update the framework by adding few components.

**Comment by thenu2003** [comment]
New issue on creating a streamlit app  ?

**Comment by thenu2003** [comment]
Okay sure , Thank you.

**Comment by thenu2003** [comment]
Okay sir Thank you , i have created it .

**Comment by AryaChakraborty** [comment]
@thenu2003 you can call me Arya.

**Comment by poojaharihar03** [comment]
Hello, I have good idea with streamlit and rag. Looking forward to work on this repo.

**Comment by DineshkumarS05** [comment]
HI have donw pojects on RAG, LlamaCpp, Langchain, Vector Databases. I would like to contribute on this project. please assign any issues for me
