### ISSUE TITLE
Adding new feature for auto commenting on new PR raised.

### ISSUE THREAD

**Issue by aRUsh-codes** [AryaChakraborty/articulus_rag#63]
### Describe the feature
This will add a feature to give instant comment to user after raising a PR

## Explanation
When we get comments on pull requests right after they're submitted, it shows us contributors that the admins are paying attention and appreciating our hard work. This helps create a friendly atmosphere where teamwork thrives, making everyone more likely to keep pitching in and staying involved.
This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs
Could you please assign me this issue under GSSOC'24 and appropriate level too

Thank You

**Comment by MohanRamSridhar** [comment]
can you please assign this issue to me under gssoc

**Comment by AryaChakraborty** [comment]
@MohanRamSridhar sorry, this issue is already assigned

**Comment by MohanRamSridhar** [comment]
hey @AryaChakraborty am ready with the PR if you don't mind can you assign this issue to me too
